### ISSUE TITLE
您好，我在使用xfy-node的时候运行node index.js有个错误

### ISSUE THREAD

**Issue by zlfdtc1983** [Samurais/xfy-node#1]
您好：
    我在使用xfy-node，按照xfy-node-getstarted这份文档进行操作。 
   运行node index.js的时候出现了错误，报错是Segmentation fault (core dumped)。
   应该是哪个地方我没配置好。
   望解答，谢谢。

**Comment by hailiang-wang** [comment]
推荐使用docker 服务的方式
```
https://hub.docker.com/r/samurais/xfyun-api/
```

文档
http://stt.chatbot.io/
